-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. Articles Table
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text,
  category text,
  author text,
  image text,
  date date default current_date,
  featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.articles enable row level security;

create policy "Articles are viewable by everyone" on public.articles
  for select using (true);

create policy "Articles are insertable by authenticated users" on public.articles
  for insert with check (auth.role() = 'authenticated');

create policy "Articles are updatable by authenticated users" on public.articles
  for update using (auth.role() = 'authenticated');

create policy "Articles are deletable by authenticated users" on public.articles
  for delete using (auth.role() = 'authenticated');

-- 2. Announcements Table
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  date date default current_date,
  urgent boolean default false,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.announcements enable row level security;

create policy "Announcements are viewable by everyone" on public.announcements
  for select using (true);

create policy "Announcements are insertable by authenticated users" on public.announcements
  for insert with check (auth.role() = 'authenticated');

create policy "Announcements are updatable by authenticated users" on public.announcements
  for update using (auth.role() = 'authenticated');

create policy "Announcements are deletable by authenticated users" on public.announcements
  for delete using (auth.role() = 'authenticated');

-- 3. Users Table (Public Profile)
-- This table mirrors auth.users for extra profile data
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  username text unique,
  name text,
  email text,
  role text default 'user',
  is_active boolean default true,
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

create policy "Users are viewable by authenticated users" on public.users
  for select using (auth.role() = 'authenticated');

create policy "Users can update their own profile" on public.users
  for update using (auth.uid() = id);

-- Allow admins (if we had specific claims) or just authenticated for now to create users in this table
-- Note: inserting here usually happens via trigger after auth.signUp, but admin might want to manually manage it.
create policy "Users can be inserted by authenticated" on public.users
  for insert with check (auth.role() = 'authenticated');

-- 4. Cultural Facts
create table if not exists public.cultural_facts (
  id bigint generated by default as identity primary key,
  title text,
  fact text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.cultural_facts enable row level security;

create policy "Facts are viewable by everyone" on public.cultural_facts
  for select using (true);

-- 5. Absent Teachers
create table if not exists public.absent_teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  subject text,
  date_from date not null,
  date_to date not null,
  duration text,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.absent_teachers enable row level security;

create policy "Absent teachers viewable by everyone" on public.absent_teachers
  for select using (true);

create policy "Absent teachers insertable by authenticated" on public.absent_teachers
  for insert with check (auth.role() = 'authenticated');

create policy "Absent teachers updatable by authenticated" on public.absent_teachers
  for update using (auth.role() = 'authenticated');

create policy "Absent teachers deletable by authenticated" on public.absent_teachers
  for delete using (auth.role() = 'authenticated');

